[project]
name = "invariant_estimation"
version = "0.0.1"
requires-python = ">= 3.12"
description = "Invariant Estimation for a Humanoid Robot in JAX"
authors = [
  { name = "Lucas Libshutz", email = "llibshutz@ihmc.org"},
  { name = "Beomyeong Park", email = "bpark@ihmc.org"},
]

dependencies = [
  "jax",
  "jaxlie",
  "ipython",
  "pyyaml",
]

[project.scripts]
docs = "invariant_estimation._docs:serve"
docs-build = "invariant_estimation._docs:build"

[dependency-groups]
dev = ["pytest"]
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.1.0",
    "sphinx>=9.1.0",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.7.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
