r"""
Java parity, tier 2: a free-running synthetic replay against the Java InvariantEKF.

Unlike `tests/replay/test_java_parity.py` (which needs a multi-gigabyte real hardware log and the
`ihmclog` decoder, neither available on every machine), this test needs nothing but the committed
golden fixture below -- it exercises the exact same InEKF math (predict, contact update, right-
invariant covariance propagation) on a fully synthetic, deterministic scenario chosen for coverage
rather than realism.

Why this was previously hard (and why it works now)
-----------------------------------------------------
`tests/replay/test_java_parity.py`'s own docstring explains why a free-running state-trajectory
comparison used to be "a poor test": the Java filter only ever *logs* the diagonal of P (as
+/-1-sigma envelope bounds via YoVariables), so a Python replica could not be re-seeded with Java's
true P and the two would drift apart from tick zero, with every disagreement looking like "it
drifts" -- no localizing power.

That constraint no longer applies here. This fixture was generated by a throwaway JUnit test
(`GenerateJavaParityFixture`, deleted after one run -- see this repo's neighboring
`ihmc-open-robotics-software` git history if it needs regenerating) that read the FULL covariance
directly from the live Java `InvariantEKF` object in-process, not from a YoVariable log -- the same
capability built today for `alex`'s `InvariantEstimatorComparisonCsvWriter`
(mocap-plus-estimator-test branch). With the true P available every tick, this test compares state
AND covariance directly, with no drift-masking possible.

The scenario (arbitrary but deterministic -- realism does not matter, only that both languages see
byte-identical inputs)
-----------------------------------------------------------------------------------------------
N=1 contact, gyro_var=1e-4, accel_var=1e-3, contact_var=1e-6, g=(0,0,-9.81), dt=1e-3, 200 ticks.
R0=I, v0=p0=(0,0,0), contact0=(0,0,-0.9), P0=0.01*I(12).

Every tick: predict(omega(t), a(t)) with
    omega(t) = (0.05 sin(0.7t), 0.03 cos(0.5t), 0.02)
    a(t)     = (0.1 sin(0.3t), 0, 9.81 + 0.05 cos(0.2t))
Every 5th tick (t % 5 == 0, t > 0): update(0, y(t), 1e-4*I) with
    y(t) = (0.02 sin(0.4t) - 0.01, 0.01 cos(0.3t), -0.85 + 0.005 sin(0.2t))

Tolerance
---------
Both sides run in float64 (this package enables `jax_enable_x64` at import, see `__init__.py`), and
the computation is a deterministic, closed-form recursion with no iterative solves that could take
different paths -- so agreement should be near machine precision, not merely "close". The tolerance
below (1e-8 relative) is deliberately tight: a loose tolerance here would hide exactly the class of
bug this test exists to catch (a sign flip, a transposed Jacobian, a forgotten rotation -- see the
group-error convention notes in `alex`'s `InvariantEstimatorNeesChecker`, which is the Java-side
sibling of this same "don't let a frame/convention bug hide behind a plausible number" concern).
"""
from __future__ import annotations

import csv
from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest

from invariant_estimation.inEKF import ekf

FIXTURE = Path(__file__).parent / "fixtures" / "java_parity_synthetic.csv"

DT = 1.0e-3
GYRO_VAR = 1.0e-4
ACCEL_VAR = 1.0e-3
CONTACT_VAR = 1.0e-6
TICKS = 200
TANGENT_SIZE = 12  # 9 + 3*1


def _read_fixture():
    with open(FIXTURE) as f:
        rows = [row for row in csv.reader(f) if row and not row[0].startswith("#")]
    header, data = rows[0], rows[1:]
    assert len(data) == TICKS, f"expected {TICKS} ticks, fixture has {len(data)}"
    return header, [[float(x) for x in row] for row in data]


def _column(header: list[str], name: str) -> int:
    return header.index(name)


@pytest.fixture(scope="module")
def fixture():
    return _read_fixture()


def test_fixture_is_present_and_well_formed(fixture):
    """Fails loudly (not a silent skip) if the golden file goes missing or is truncated -- this
    fixture has no fallback the way the real-hardware-log tests do."""
    header, data = fixture
    assert len(data) == TICKS
    assert len(header) == 19 + 78  # tick + 9 R + 3 v + 3 p + 3 d + 78 upper-triangle P entries


def test_java_and_jax_inekf_agree_tick_by_tick(fixture):
    header, data = fixture

    filt = ekf.create(1, gyro_var=GYRO_VAR, accel_var=ACCEL_VAR, contact_var=CONTACT_VAR, dt=DT)
    state = ekf.initialize(
        filt,
        rotation=jnp.eye(3),
        velocity=jnp.zeros(3),
        position=jnp.zeros(3),
        contacts=jnp.array([[0.0, 0.0, -0.9]]),
        covariance=0.01 * jnp.eye(TANGENT_SIZE),
    )

    r_cols = [_column(header, f"R{i}{j}") for i in range(3) for j in range(3)]
    v_cols = [_column(header, c) for c in ("vx", "vy", "vz")]
    p_cols = [_column(header, c) for c in ("px", "py", "pz")]
    d_cols = [_column(header, c) for c in ("dx", "dy", "dz")]
    p_upper_cols = {(i, j): _column(header, f"P_{i}_{j}") for i in range(TANGENT_SIZE) for j in range(i, TANGENT_SIZE)}

    worst_state_err = 0.0
    worst_cov_err = 0.0
    worst_tick = -1

    for tick in range(TICKS):
        t = tick * DT
        omega = jnp.array([0.05 * np.sin(0.7 * t), 0.03 * np.cos(0.5 * t), 0.02])
        accel = jnp.array([0.1 * np.sin(0.3 * t), 0.0, 9.81 + 0.05 * np.cos(0.2 * t)])
        state = ekf.predict(filt, state, omega, accel)

        if tick > 0 and tick % 5 == 0:
            y = jnp.array(
                [0.02 * np.sin(0.4 * t) - 0.01, 0.01 * np.cos(0.3 * t), -0.85 + 0.005 * np.sin(0.2 * t)]
            )
            body_cov = 1.0e-4 * jnp.eye(3)
            state, _ = ekf.update(filt, state, 0, y, body_cov)

        row = data[tick]
        java_r = np.array([row[c] for c in r_cols]).reshape(3, 3)
        java_v = np.array([row[c] for c in v_cols])
        java_p = np.array([row[c] for c in p_cols])
        java_d = np.array([row[c] for c in d_cols])

        jax_r = np.asarray(state.R)
        jax_v = np.asarray(state.v)
        jax_p = np.asarray(state.p)
        jax_d = np.asarray(state.d[0])

        state_err = max(
            np.abs(jax_r - java_r).max(),
            np.abs(jax_v - java_v).max(),
            np.abs(jax_p - java_p).max(),
            np.abs(jax_d - java_d).max(),
        )
        if state_err > worst_state_err:
            worst_state_err = state_err
            worst_tick = tick

        jax_p_full = np.asarray(state.P)
        for (i, j), col in p_upper_cols.items():
            java_pij = row[col]
            jax_pij = jax_p_full[i, j]
            err = abs(jax_pij - java_pij)
            scale = max(abs(java_pij), 1.0e-9)
            worst_cov_err = max(worst_cov_err, err / scale)

    assert worst_state_err < 1.0e-8, (
        f"Java/JAX InEKF state disagreement peaked at tick {worst_tick}: {worst_state_err:.3e} "
        f"(rotation matrix entries, velocity, position, or contact position) -- see this file's "
        f"docstring for the tight-tolerance rationale."
    )
    assert worst_cov_err < 1.0e-6, (
        f"Java/JAX InEKF covariance disagreement (relative) peaked at {worst_cov_err:.3e}."
    )
